# Generated by Django 3.1.7 on 2022-08-10 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polls',
            options={'verbose_name_plural': 'Polls'},
        ),
        migrations.RemoveField(
            model_name='polls',
            name='vote',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_app.polls')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
