# Generated by Django 3.1.7 on 2022-08-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0002_auto_20220810_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
