# Generated by Django 3.1.7 on 2022-12-09 13:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0007_remove_polls_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='choices',
            name='polls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls_app.polls'),
        ),
    ]
