# Generated by Django 3.1.7 on 2022-12-09 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0008_auto_20221209_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
