# Generated by Django 3.1.7 on 2022-12-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0009_auto_20221209_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
