# Generated by Django 3.1.7 on 2022-12-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0010_auto_20221209_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='expire_at',
        ),
    ]
